services:
  - type: static
    name: elvora-web
    env: static
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /sw.js
        destination: /sw.js
      - type: rewrite
        source: /manifest.webmanifest
        destination: /manifest.webmanifest
      - type: rewrite
        source: /(.*\.(css|js|png|jpg|jpeg|gif|webp|svg|ico|txt|json))
        destination: /$1
      - type: rewrite
        source: /.*
        destination: /index.html
    headers:
      - path: /sw.js
        name: Cache-Control
        value: no-cache
      - path: /manifest.webmanifest
        name: Cache-Control
        value: no-cache
      - path: /index.html
        name: Cache-Control
        value: no-cache
